#!/bin/bash
set -eux

apt-get -y --force-yes install apt-transport-https ca-certificates
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-$DIB_RELEASE main" >> /etc/apt/sources.list.d/docker.list
apt-get update
apt-get purge lxc-docker
apt-get -y --force-yes install linux-image-extra-$(uname -r)
apt-get -y --force-yes install docker-engine

sed -i '2i docker start configurator' /etc/rc.local
