#! /bin/bash
set -eu

# copy the reference_configurator folder to VM at /home/ubuntu/
mv /root/reference_configurator /home/ubuntu/
ls -lR /home/ubuntu/

# copy the pecan.service file
cp -L /home/ubuntu/reference_configurator/config/pecan.service /etc/systemd/system/pecan.service
chmod 777 /etc/systemd/system/pecan.service
ls -l /etc/systemd/system/pecan.service

cp -L /home/ubuntu/reference_configurator/config/pecan.service /etc/systemd/system/multi-user.target.wants/pecan.service
chmod 755 /etc/systemd/system/multi-user.target.wants/pecan.service
ls -l /etc/systemd/system/multi-user.target.wants/pecan.service

# make pecan service to launch during each system boot
cp -rL /home/ubuntu/reference_configurator/bin/nfp-pecan /usr/bin/nfp-pecan
chmod 777 /usr/bin/nfp-pecan
ls -l /usr/bin/nfp-pecan
chmod 777 /home/ubuntu/reference_configurator/bin/nfp-pecan
ls -l /home/ubuntu/reference_configurator/bin/nfp-pecan
