""" Constants for Topic of all the REST Handlers"""

FWAAS_RPC_TOPIC = "FWAAS_RPC_TOPIC"
LBAAS_RPC_TOPIC = "LBAAS_RPC_TOPIC"
VPNAAS_RPC_TOPIC = "VPNAAS_RPC_TOPIC"
GENERIC_CONFIG_RPC_TOPIC = "GENERIC_CONFIG_RPC_TOPIC"
HEALTH_MONITOR_RPC_TOPIC = "HEALTH_MONITOR_RPC_TOPIC"

