#! /bin/bash
set -eu

# copy the reference_configurator folder to VM at /home/ubuntu/
cp -rL ${SERVICE_GIT_PATH}/reference_configurator ${TMP_MOUNT_PATH}/home/ubuntu/

# copy the pecan.service file
sudo cp -L ${SERVICE_GIT_PATH}/reference_configurator/config/pecan.service ${TMP_MOUNT_PATH}/etc/systemd/system/pecan.service
sudo chmod 777 ${TMP_MOUNT_PATH}/etc/systemd/system/pecan.service
sudo cp -L ${SERVICE_GIT_PATH}/reference_configurator/config/pecan.service ${TMP_MOUNT_PATH}/etc/systemd/system/multi-user.target.wants/pecan.service
sudo chmod 755 ${TMP_MOUNT_PATH}/etc/systemd/system/multi-user.target.wants/pecan.service

# make pecan service to launch during each system boot
sudo cp -rL ${SERVICE_GIT_PATH}/reference_configurator/bin/nfp-pecan ${TMP_MOUNT_PATH}/usr/bin/nfp-pecan
sudo chmod 777 ${TMP_MOUNT_PATH}/usr/bin/nfp-pecan

# python site-packages workaround
sudo cp -rf /home/ubuntu/.local/lib/python2.7/site-packages/* /usr/lib/python2.7/dist-packages/.

